// Build-time configuration: this file is overwritten by CI with actual signing status.
// Do NOT modify this file directly — it is generated by .github/workflows/build.yml.
module.exports = { signed: false };
